services:
  - type: web
    name: ansiedad-backend
    env: python
    runtime: python-3.11.9
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    rootDir: backend

  - type: static
    name: ansiedad-frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    rootDir: frontend
    envVars:
      - key: VITE_API_URL
        value: https://ansiedad-backend.onrender.com